import axios from "axios";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "@/components/Header";

declare global {
  interface Window {
    MyNamespace: any;
  }
}

interface MockData {
  name: string | "";
  email: string;
  phone: string;
  address: string;
}

const Home = () => {
  const [currentDomain, setCurrentDomain] = useState<string>("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const currentUrl = window.location.href;
      const currentDomain = new URL(currentUrl).hostname;
      setCurrentDomain(currentDomain);
    }
  }, [currentDomain]);

  return (
    <>
      <Head>
        <title>Test Multi Domain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#1a1a1a] border-b border-[#ffffff42]">
        <Header />
      </div>
      <main className="flex flex-col justify-between items-center min-h-screen">
        <span className="p-2 text-3xl font-bold">
          Welcome to <span className="text-purple-600">{currentDomain}</span>
        </span>
      </main>
    </>
  );
};

export default Home;
